services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
        env_file: 
          -backend/.env
    environment:
      PGURI: ${PGURI}
    ports: "3000:3000"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: ./data:/var/lib/postgresql/data
    ports: "5432:5432"
healthcheck:
  interval: 1s